<?php
$data = array (
  159 => 
  array (
    'cat_id' => '159',
    'cat_name' => '女鞋',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 0,
    'id' => '159',
    'name' => '女鞋',
  ),
  174 => 
  array (
    'cat_id' => '174',
    'cat_name' => '单鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 1,
    'id' => '174',
    'name' => '单鞋',
  ),
  235 => 
  array (
    'cat_id' => '235',
    'cat_name' => '新款区',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '235',
    'name' => '新款区',
  ),
  232 => 
  array (
    'cat_id' => '232',
    'cat_name' => '中跟鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '232',
    'name' => '中跟鞋',
  ),
  229 => 
  array (
    'cat_id' => '229',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '229',
    'name' => '拖鞋',
  ),
  236 => 
  array (
    'cat_id' => '236',
    'cat_name' => '特价区',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '236',
    'name' => '特价区',
  ),
  233 => 
  array (
    'cat_id' => '233',
    'cat_name' => '休闲鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '233',
    'name' => '休闲鞋',
  ),
  230 => 
  array (
    'cat_id' => '230',
    'cat_name' => '帆布鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '230',
    'name' => '帆布鞋',
  ),
  228 => 
  array (
    'cat_id' => '228',
    'cat_name' => '凉鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '228',
    'name' => '凉鞋',
  ),
  234 => 
  array (
    'cat_id' => '234',
    'cat_name' => '运动鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '234',
    'name' => '运动鞋',
  ),
  231 => 
  array (
    'cat_id' => '231',
    'cat_name' => '平跟鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '231',
    'name' => '平跟鞋',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '男鞋',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '9',
    'sort_order' => '2',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '140',
    'name' => '男鞋',
  ),
  237 => 
  array (
    'cat_id' => '237',
    'cat_name' => '凉鞋',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '237',
    'name' => '凉鞋',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '商务皮鞋',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '9',
    'sort_order' => '41',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '148',
    'name' => '商务皮鞋',
  ),
  238 => 
  array (
    'cat_id' => '238',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '42',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '238',
    'name' => '拖鞋',
  ),
  239 => 
  array (
    'cat_id' => '239',
    'cat_name' => '休闲鞋',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '239',
    'name' => '休闲鞋',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => '休闲皮鞋',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '151',
    'name' => '休闲皮鞋',
  ),
  241 => 
  array (
    'cat_id' => '241',
    'cat_name' => '新品区',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '241',
    'name' => '新品区',
  ),
  240 => 
  array (
    'cat_id' => '240',
    'cat_name' => '帆布鞋',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '240',
    'name' => '帆布鞋',
  ),
  242 => 
  array (
    'cat_id' => '242',
    'cat_name' => '特价区',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '242',
    'name' => '特价区',
  ),
  243 => 
  array (
    'cat_id' => '243',
    'cat_name' => '运动鞋',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 0,
    'id' => '243',
    'name' => '运动鞋',
  ),
  252 => 
  array (
    'cat_id' => '252',
    'cat_name' => '新品区',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '252',
    'name' => '新品区',
  ),
  249 => 
  array (
    'cat_id' => '249',
    'cat_name' => '网球鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '249',
    'name' => '网球鞋',
  ),
  246 => 
  array (
    'cat_id' => '246',
    'cat_name' => '帆布鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '246',
    'name' => '帆布鞋',
  ),
  253 => 
  array (
    'cat_id' => '253',
    'cat_name' => '特价区',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '253',
    'name' => '特价区',
  ),
  250 => 
  array (
    'cat_id' => '250',
    'cat_name' => '训练鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '250',
    'name' => '训练鞋',
  ),
  247 => 
  array (
    'cat_id' => '247',
    'cat_name' => '休闲鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '247',
    'name' => '休闲鞋',
  ),
  244 => 
  array (
    'cat_id' => '244',
    'cat_name' => '板鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '244',
    'name' => '板鞋',
  ),
  251 => 
  array (
    'cat_id' => '251',
    'cat_name' => '足球鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '251',
    'name' => '足球鞋',
  ),
  248 => 
  array (
    'cat_id' => '248',
    'cat_name' => '篮球鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '248',
    'name' => '篮球鞋',
  ),
  245 => 
  array (
    'cat_id' => '245',
    'cat_name' => '跑步鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '245',
    'name' => '跑步鞋',
  ),
  254 => 
  array (
    'cat_id' => '254',
    'cat_name' => '户外',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '254',
    'name' => '户外',
  ),
  262 => 
  array (
    'cat_id' => '262',
    'cat_name' => '新品',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '262',
    'name' => '新品',
  ),
  259 => 
  array (
    'cat_id' => '259',
    'cat_name' => '徒步鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '259',
    'name' => '徒步鞋',
  ),
  260 => 
  array (
    'cat_id' => '260',
    'cat_name' => '布鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '260',
    'name' => '布鞋',
  ),
  255 => 
  array (
    'cat_id' => '255',
    'cat_name' => '户外鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '255',
    'name' => '户外鞋',
  ),
  261 => 
  array (
    'cat_id' => '261',
    'cat_name' => '登山鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '261',
    'name' => '登山鞋',
  ),
  256 => 
  array (
    'cat_id' => '256',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '256',
    'name' => '拖鞋',
  ),
  257 => 
  array (
    'cat_id' => '257',
    'cat_name' => '休闲鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '257',
    'name' => '休闲鞋',
  ),
  258 => 
  array (
    'cat_id' => '258',
    'cat_name' => '凉鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '258',
    'name' => '凉鞋',
  ),
  194 => 
  array (
    'cat_id' => '194',
    'cat_name' => '童鞋',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '11',
    'goods_num' => '5',
    'level' => 0,
    'id' => '194',
    'name' => '童鞋',
  ),
  196 => 
  array (
    'cat_id' => '196',
    'cat_name' => '跑步鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '196',
    'name' => '跑步鞋',
  ),
  199 => 
  array (
    'cat_id' => '199',
    'cat_name' => '帆布鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '199',
    'name' => '帆布鞋',
  ),
  203 => 
  array (
    'cat_id' => '203',
    'cat_name' => '户外鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '203',
    'name' => '户外鞋',
  ),
  206 => 
  array (
    'cat_id' => '206',
    'cat_name' => '凉鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '206',
    'name' => '凉鞋',
  ),
  195 => 
  array (
    'cat_id' => '195',
    'cat_name' => '篮球鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '195',
    'name' => '篮球鞋',
  ),
  198 => 
  array (
    'cat_id' => '198',
    'cat_name' => '休闲鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '198',
    'name' => '休闲鞋',
  ),
  202 => 
  array (
    'cat_id' => '202',
    'cat_name' => '登山鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '202',
    'name' => '登山鞋',
  ),
  205 => 
  array (
    'cat_id' => '205',
    'cat_name' => '中筒靴',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '205',
    'name' => '中筒靴',
  ),
  197 => 
  array (
    'cat_id' => '197',
    'cat_name' => '板鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '197',
    'name' => '板鞋',
  ),
  201 => 
  array (
    'cat_id' => '201',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '201',
    'name' => '拖鞋',
  ),
  204 => 
  array (
    'cat_id' => '204',
    'cat_name' => '短靴',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '204',
    'name' => '短靴',
  ),
);
?>