<?php
$data = array (
  0 => 
  array (
    'cat_id' => '159',
    'cat_name' => '女鞋',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '140',
    'cat_name' => '男鞋',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '9',
    'sort_order' => '2',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '243',
    'cat_name' => '运动鞋',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '254',
    'cat_name' => '户外',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '194',
    'cat_name' => '童鞋',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '11',
    'goods_num' => '5',
  ),
  5 => 
  array (
    'cat_id' => '237',
    'cat_name' => '凉鞋',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '148',
    'cat_name' => '商务皮鞋',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '9',
    'sort_order' => '41',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  7 => 
  array (
    'cat_id' => '238',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '42',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '239',
    'cat_name' => '休闲鞋',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '151',
    'cat_name' => '休闲皮鞋',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  10 => 
  array (
    'cat_id' => '241',
    'cat_name' => '新品区',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '240',
    'cat_name' => '帆布鞋',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '242',
    'cat_name' => '特价区',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '174',
    'cat_name' => '单鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  14 => 
  array (
    'cat_id' => '235',
    'cat_name' => '新款区',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '232',
    'cat_name' => '中跟鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '229',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '236',
    'cat_name' => '特价区',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '233',
    'cat_name' => '休闲鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '230',
    'cat_name' => '帆布鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '228',
    'cat_name' => '凉鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '234',
    'cat_name' => '运动鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '231',
    'cat_name' => '平跟鞋',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '196',
    'cat_name' => '跑步鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '199',
    'cat_name' => '帆布鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '203',
    'cat_name' => '户外鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '206',
    'cat_name' => '凉鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '195',
    'cat_name' => '篮球鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '198',
    'cat_name' => '休闲鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '202',
    'cat_name' => '登山鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '205',
    'cat_name' => '中筒靴',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '197',
    'cat_name' => '板鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '201',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '204',
    'cat_name' => '短靴',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '252',
    'cat_name' => '新品区',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '249',
    'cat_name' => '网球鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '246',
    'cat_name' => '帆布鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '253',
    'cat_name' => '特价区',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '250',
    'cat_name' => '训练鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '247',
    'cat_name' => '休闲鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '244',
    'cat_name' => '板鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '251',
    'cat_name' => '足球鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '248',
    'cat_name' => '篮球鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '245',
    'cat_name' => '跑步鞋',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '262',
    'cat_name' => '新品',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '259',
    'cat_name' => '徒步鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '260',
    'cat_name' => '布鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '255',
    'cat_name' => '户外鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '261',
    'cat_name' => '登山鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '256',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '257',
    'cat_name' => '休闲鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '258',
    'cat_name' => '凉鞋',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>